name: "Go Rest API"

services:
  postgres:
    image: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ~/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - GoRestNetwork

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT} 
    networks:
      - GoRestNetwork

networks:
  GoRestNetwork: